shepherd:
  github-token: ${GITHUB_PERSONAL_ACCESS_TOKEN:#{null}}
  first-responder-llm:
    model: gpt-4.1-mini
    temperature: 0.3
  researcher-llm:
    model: gpt-4.1-mini
  profile-categories:
    - friend
    - competitor
    - contributor
  programming-languages:
    - Java
    - Kotlin
    - Python
    - JavaScript
    - TypeScript
    - Go
    - Ruby
    - C#
    - C++
    - C
    - Scala
    - Rust

  frameworks:
    - Spring
    - React
    - Angular
    - .NET
    - Ruby on Rails
    - Node.js
    - Flask
    - Laravel
  
  
  repositories-to-monitor:
    - https://github.com/embabel/embabel-agent
  issue-labels:
    - bug
    - enhancement
    - documentation
    - invalid


database:
  dataSources:
    neo:
      type: NEO4J
      userName: neo4j
      password: brahmsian
      host: localhost
      port: 7687
      databaseName: neo4j